### PR TITLE
Boostrap 4 - Newsweek Magazine - Solo Project

### PR DESCRIPTION
**Pull request by guirecordon**
**In this project I built a mock-up page of the Newsweek homepage magazine as follows:**

- I used Bootstrap and I chose to download it to my root file and reference it locally from my HTML;
- I used Boostrap markup for the entire layout and as much as possible for the complementing style of the website;
- I worked with three break-points, the so-called 'sm, md, and lg' (Bootstrap breakpoints);
- I also used Bootstrap's built-in properties to build the navbar and make it collapse in a responsive way;
I paid particular attention to details such as icons, section heading logos, image positioning, etc.

Thanks in advance for the review.

Gui Recordon

### CODE REVIEW

**Review by rOluochKe — CHANGES_REQUESTED** [review]
Hello @guirecordon 
### You have done really well so far in this project :clap: You are close to finish, however, you have a few issues to solve.
- On mobile devices, in the magazine section, the images are to go full width
full width on mobile
- On medium devices, in the newsletter section, the content is to go full width, meaning image half and the text, don't make the text block, refer how you have done subscribe
medium screen
### make these changes and resubmit for another code review. Good luck.
- Happy coding!

**Comment by guirecordon** [comment]
Hi, Raymond. Thanks for your review. I fixed those two issues you pointed out. Both of those sections' images should go full width when prompted now. 
I'll be sending a new request for review. Thanks again!

**Comment by thsvr** [comment]
### **STATUS: CHANGES REQUIRED** :+1: 

Hi @guirecordon :smile: 
**Your project looks beautiful and professional**, you are almost there :muscle: 

On mobile devices, in the magazine section, as Raymond mentioned, the images are to go full width. I printed both to you see the difference :smile_cat: 
Can you please fix it and then submit for another review?

### **ORIGINAL:**
original1

### **YOURS:**
students1


If you have any questions, don't hesitate to contact me through slack [@thaís Vieira Azevedo](url)

### **Happy coding and good luck on the next review!** :computer: 

_Project reviewed by Thaís Vieira (TSE)_

**Comment by guirecordon** [comment]
Hi, Thaís. Thank you for your review. I thought the changes I made previously were doing the trick, but you're right. The desired result was just not quite there yet. After testing several times I think it's safe to say the images should be working now.
While I was at it, I updated one more photo that was blurred and added it as a fallback image for a better user experience on mobile devices. 
Thanks again, abraços!

**Comment by Dandush03** [comment]
### :heavy_check_mark: Project Approve :boom:  :checkered_flag:
# Hey @guirecordon   :hand: 
### Great Job so Far :grey_exclamation: :grey_exclamation: :muscle: :smiley: 

### Following Previous Reviews and Seeing you Have Made Required Changes. 
### The project Looks Great.:grey_exclamation::wink:

### Good Luck in your Next Assigment
### Happy coding:computer: 
#### Daniel Laloush

**Comment by guirecordon** [comment]
Thanks, Daniel!

**Pull request merged**
